using Microsoft.CodeAnalysis;
using System;

namespace SourceGenerator
{
    [Generator]
    public class HelloSourceGenerator : ISourceGenerator
    {
        public void Execute(GeneratorExecutionContext context)
        {
            var deterministicBuild = context.Compilation.Options.Deterministic;
            var deterministicBuildStr = deterministicBuild.ToString().ToLower();
            var ticks = (deterministicBuild ? 0L : DateTime.UtcNow.Ticks).ToString();
            string source = $@"// <auto-generated/>
using System;

namespace SourceGeneratorExample
{{
    public static class Helper
    {{
        public static readonly long BuildTime = {ticks};
        public static readonly bool DeterministicBuild = {deterministicBuildStr};      
    }}
}}
";
            context.AddSource($"Helper.g.cs", source);
        }

        public void Initialize(GeneratorInitializationContext context)
        {
            // No initialization required for this one
        }
    }
}